services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      DATALAKE_ADDR: localhost:9091
    networks:
      - openzdm
    ports:
      - 80:80

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: apicurio-registry
      POSTGRES_USER: apicurio
      POSTGRES_PASSWORD: openzdm
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - openzdm

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883" #default mqtt port
      # - "9001:9001" #default mqtt port for websockets
    volumes:
      - ./mosquitto/config:/mosquitto/config:rw
      - ./mosquitto/data:/mosquitto/data:rw
      - ./mosquitto/log:/mosquitto/log:rw
    restart: always
    networks:
      - openzdm

  registry:
    image: registry:2
    container_name: registry
    restart: always
    ports:
      - 5001:5000
    volumes:
      - ./registry:/var/lib/registry

  # adminer:
  #   image: adminer
  #   ports:
  #     - 8082:8080
  #   networks:
  #     - openzdm

  apicurio:
    image: apicurio/apicurio-registry-sql:latest-release
    depends_on:
      - postgres
    container_name: apicurio
    networks:
      - openzdm
    ports:
      - 8080:8080
    environment:
      REGISTRY_DATASOURCE_URL: jdbc:postgresql://postgres/apicurio-registry
      REGISTRY_DATASOURCE_USERNAME: apicurio
      REGISTRY_DATASOURCE_PASSWORD: openzdm

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222" # Client port
      - "8222:8222" # HTTP monitoring port
      - "6222:6222" # Cluster port
    networks:
      - openzdm

networks:
  openzdm:
    external: true

volumes:
  pgdata:
